# Generated by Django 6.0.2 on 2026-02-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoprice',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='cryptoprice',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
