# Generated by Django 6.0.2 on 2026-02-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cryptoprice_price_alter_cryptoprice_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('target_price', models.DecimalField(decimal_places=10, max_digits=30)),
                ('alert_type', models.CharField(choices=[('ABOVE', 'Above'), ('BELOW', 'Below')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
